### ISSUE TITLE
src/main/java/com/logindb/logindb/repository/MemberRepository.java

### ISSUE THREAD

**Issue by Yaklede** [LEEDAESEUNG-Developer/login-DB#3]
//회원 조회
    Member findMemberByIdAndPwd(LoginDto LoginDto);

    //회원 조회 아이디만 (단수)
    Member findMemberById(String id);

================================

`Optional<Member> findMemberByIdAndPwd(LoginDto loginDto);`

`Optional<Member> findMemberById(String id);`

**Comment by Lee-Backend-Developer** [comment]
complete
