### ISSUE TITLE
src/main/java/com/logindb/logindb/service/MemberServiceImpl.java

### ISSUE THREAD

**Issue by Yaklede** [LEEDAESEUNG-Developer/login-DB#4]
`
    @Override
    public void createMember(MemberInsertDto dto) {
        // 회원 검사
        try {
            Member memberById = memberRepository.findMemberById(dto.getId());
            if (memberById != null) throw new MemberCreateError();
            memberRepository.insertMember(dto);
        } catch (MemberCreateError e) {
            log.debug(e.getMessage());
        }
    }

    @Override
    public Member login(LoginDto dto) {
        return memberRepository.findMemberByIdAndPwd(dto);
    }
===========================================
`
 public void createMember(MemberInsertDto dto) {
        try {
            memberRepository.findMemberById(dto.getId()).orElseThrow( () -> new MemberNotCreateException());
            memberRepository.insertMember(dto);
        } catch (MemberNotCreateException e) {
            log.debug(e.getMessage());
        }
    }
회원검사
`

`
public Member login(LoginDto dto) {
        try{
            memberRepository.findMemberByIdAndPwd(dto).orElseThrow( () -> new BadCredentialException());
       } catch(BadCredentialExcetpion e) {
           log.debug(e.getMessage());
       }
 }에러로직 추가바람`

**Comment by Lee-Backend-Developer** [comment]
complete
